version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  prometheus:
    restart: unless-stopped
    build:
      context: ./prometheus
    image: prometheus:vd-local
    volumes:
      - prom-data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CLIENT=${COMPOSE_FILE}
    entrypoint: choose-config.sh
    command: ["/bin/prometheus", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles"]
    <<: *logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.prom-vd.entrypoints=web,websecure
      - traefik.http.routers.prom-vd.rule=Host(`${PROM_HOST}.${DOMAIN}`)
      - traefik.http.routers.prom-vd.tls.certresolver=letsencrypt
      - traefik.http.services.prom-vd.loadbalancer.server.port=9090

volumes:
  prom-data:
