version: "3.4"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "100m"

services:
  vouch:
    image: attestant/vouch:${VOUCH_DOCKER_TAG}
    restart: unless-stopped
    command: ["--base-dir=/config"]
    volumes:
      - ./config/vouch${VOUCH_INSTANCE}.yml:/config/vouch.yml:ro
      - ./config/certs:/config/certs:ro
    <<: *logging

