version: "3.4"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "100m"

services:
  vouch:
    image: attestant/vouch:${VOUCH_DOCKER_TAG}
    restart: unless-stopped
    command: ["--base-dir=/config"]
    volumes:
      - ./config/vouch${VOUCH_INSTANCE}.yml:/config/vouch.yml:ro
      - ./config/vouch-ee.json:/config/vouch-ee.json:ro
      - ./config/certs:/config/certs:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.${MEV_HOST:-mev}.service=${MEV_HOST:-mev}
      - traefik.http.routers.${MEV_HOST:-mev}.entrypoints=websecure
      - traefik.http.routers.${MEV_HOST:-mev}.rule=Host(`${MEV_HOST:-mev}.${DOMAIN}`)
      - traefik.http.routers.${MEV_HOST:-mev}.tls.certresolver=letsencrypt
      - traefik.http.services.${MEV_HOST:-mev}.loadbalancer.server.port=18550
    <<: *logging

