scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: file-discovery
    file_sd_configs:
      - files:
          - "/etc/prometheus/file_sd/*.yml"
